- hosts: all
  gather_facts: true
  become: true
  pre_tasks:

  - name: Install updates CentOS
    yum:
      update_cache: yes
    when: ansible_distribution == "CentOS"

  - name: Install updates Ubuntu
    apt:
      update_cache: yes
    when: ansible_distribution == "Ubuntu"

# --------------------------------------

- hosts: webservers
  become: true
  tasks:

  - name: Install nginx and php for Ubuntu
    apt:
      name: nginx
      state: latest
    when: ansible_distribution == "Ubuntu"
    notify: "Restart the nginx server"

  - name: Install php and modules
    apt:  
      name: 
        - php-fpm
        - php-mysql
        - php-curl
        - php-gd
        - php-mbstring
      state: present
    when: ansible_distribution == "Ubuntu"

  
  handlers:
    - name: Restart the nginx server
      become: true
      service: name=nginx state=restarted 


- hosts: dbservers
  become: true
  tasks:
  - name: Install mariadb
    apt:
      name: mariadb-server
      state: latest
    when: ansible_distribution == "Ubuntu" 
