- name: Install updates CentOS
  yum:
      update_cache: yes
  changed_when: false
  when: ansible_distribution == "CentOS"

- name: Install updates Ubuntu
  apt:
      update_cache: yes
  changed_when: false
  when: ansible_distribution == "Ubuntu"
